name: nexrad
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8 # Python version 3.6
  - black # clean code and make it pretty
  - cartopy # mapping
  - dask # Parallel processing library
  - matplotlib # mapping
  - mypy # type checking
  - netcdf4 # Wrapper for netcdf4
  - numpy # N-d array and numerics
  - pandas # Labeled array library
  - pylint # catch errors before you make them
  - snakemake
  - snakefmt
  - tqdm # Nice progressbar for longer computations
  - xarray # N-d labeled array library
